import type { Metadata } from "next";
import { Dancing_Script, Poppins, Raleway } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/hooks/AppContext";
import React from "react";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"], // specify one or multiple weights
  variable: "--font-poppins",
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${raleway.variable} ${dancingScript.variable} ${poppins.variable} antialiased`}
      >
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
